version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: RestApiWdcContainer
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=RestApiWdc

    volumes:
      - ./storage:/var/lib/postgresql/data